In [3]:
import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [13]:
sample = torch.randn(5, 3).to(device)

print(sample)

lins = nn.Linear(3, 6).to(device)

print(lins(sample))   

print(lins.weight)

tensor([[ 0.8707, -0.5997,  0.1352],
        [ 1.0290,  2.0745,  0.3960],
        [ 0.7930, -0.3834, -0.4516],
        [-1.1449, -0.2077, -1.2865],
        [ 3.4425, -0.1724,  1.0075]], device='cuda:0')
tensor([[-0.7889,  0.0801,  0.4141,  0.2791, -0.7523,  0.3144],
        [-0.3024, -0.6704, -1.1177,  0.5613,  0.4372,  0.3789],
        [-0.8703,  0.2231,  0.3824,  0.1303, -0.6341,  0.1489],
        [-0.3441, -0.2168,  0.0742, -0.3694,  0.4775,  0.4835],
        [-1.4288,  0.5811,  0.4914,  0.9280, -1.9260, -0.1999]],
       device='cuda:0', grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.3643,  0.1788,  0.2529],
        [ 0.3712, -0.2645, -0.3904],
        [ 0.1849, -0.5663, -0.1792],
        [ 0.1524,  0.0712,  0.2597],
        [-0.5505,  0.4729,  0.0458],
        [-0.3128,  0.0107,  0.3274]], device='cuda:0', requires_grad=True)


In [11]:
multi_ma = torch.mm(sample, sample.T)

print(f'Matrix 1: {sample.shape} x Matrix 2: {sample.T.shape} = {multi_ma.shape}')

Matrix 1: torch.Size([5, 3]) x Matrix 2: torch.Size([3, 5]) = torch.Size([5, 5])


In [12]:
multi_ma = sample.mm( sample.T)

print(f'Matrix 1: {sample.shape} x Matrix 2: {sample.T.shape} = {multi_ma.shape}')

Matrix 1: torch.Size([5, 3]) x Matrix 2: torch.Size([3, 5]) = torch.Size([5, 5])


In [55]:

token_tensor = torch.zeros(size=(10**3, 3), dtype=torch.int8).to(device)

counter = 0
for male in range(0,10):
    for female in range(0,10):
        for aborted in range(0,10):
            token_tensor[counter,:] = torch.tensor([male,female,aborted], requires_grad=False)
            counter += 1



class EncoderDecoder(nn.Module):
    def __init__(self, token_tensor) -> None:
        super().__init__()
        self.tokens = {}
        for i, f in enumerate(token_tensor):
            self.tokens[torch.tensor(f).clone().detach()] = i
        
        self.f = {value: key for key, value in self.tokens.items()}
    
    def encode(self, x:torch.tensor):
        return self.tokens[x]

    def decode(self, x:torch.long):
        return self.f[x]


ed_flowers = EncoderDecoder(token_tensor=token_tensor)

print(ed_flowers.decode(8))
print(ed_flowers.encode(torch.tensor([0,1,0],device='cuda', dtype=torch.int8)))


tensor([0, 0, 8], device='cuda:0', dtype=torch.int8)


C:\Users\jacob\AppData\Local\Temp\ipykernel_20548\4077543698.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.tokens[torch.tensor(f).clone().detach()] = i


KeyError: tensor([0, 1, 0], device='cuda:0', dtype=torch.int8)